package com.hk.luatela.patch;

import com.hk.str.HTMLText;

import java.io.File;
import java.io.PrintWriter;

public class PatchExport
{
	private final LuaBase base;
	private final PatchComparison comparison;

	public PatchExport(LuaBase base, PatchComparison comparison)
	{
		this.base = base;
		this.comparison = comparison;
	}

	public HTMLText toLua(HTMLText txt)
	{
		txt.prln("--[[").tabUp();
		txt.prln("Generated by Lua Tela");
		txt.prln("");
		txt.tabDown().prln("]]");

		return txt;
	}
}
